# Generated by Django 4.2.5 on 2023-09-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0002_test_delete_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='licence',
            new_name='data_1',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='data_2',
        ),
    ]
