# Generated by Django 4.2.5 on 2023-09-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0003_rename_licence_test_data_1_rename_name_test_data_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
