# Generated by Django 4.2.5 on 2023-09-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
