# Generated by Django 4.2.5 on 2023-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0004_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='labgroups',
            name='signed_up_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labs',
            name='minim_students',
            field=models.IntegerField(default=2),
        ),
    ]
