# Generated by Django 4.1.7 on 2023-09-16 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0005_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('labs_amount', models.IntegerField()),
                ('is_visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_students', models.IntegerField()),
                ('is_visible', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmoweb.courses')),
            ],
        ),
        migrations.CreateModel(
            name='LabGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('place', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmoweb.labs')),
            ],
        ),
    ]
