# Generated by Django 4.2.5 on 2023-10-15 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0007_labs_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField()),
                ('filename', models.CharField(max_length=50)),
                ('report_status', models.IntegerField()),
                ('comments', models.TextField()),
                ('grade', models.IntegerField()),
                ('grading_date', models.DateField()),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grader', to=settings.AUTH_USER_MODEL)),
                ('lab_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmoweb.labgroups')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
