# Generated by Django 4.2.5 on 2023-10-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
