# Generated by Django 4.2.5 on 2023-10-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0009_alter_report_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='grading_date',
            field=models.DateField(null=True),
        ),
    ]
