# Generated by Django 4.2.5 on 2023-10-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0008_alter_labs_max_students'),
        ('ilmoweb', '0010_alter_report_grading_date'),
    ]

    operations = [
    ]
