# Generated by Django 4.2.5 on 2023-10-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0011_merge_20231015_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filename',
            field=models.FileField(null=True, upload_to='ilmoweb/static/upload'),
        ),
    ]
