# Generated by Django 4.2.5 on 2023-10-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0012_alter_report_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filename',
            field=models.FileField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='report',
            name='send_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
