# Generated by Django 4.2.5 on 2023-10-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0017_labgroups_assistant'),
        ('ilmoweb', '0017_labgroups_deleted'),
    ]

    operations = [
    ]
