# Generated by Django 4.2.5 on 2023-11-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0018_merge_0017_labgroups_assistant_0017_labgroups_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_name',
            field=models.CharField(default=''),
        ),
    ]
