# Generated by Django 4.2.5 on 2023-11-16 13:51

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0021_remove_user_student_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=django_cryptography.fields.encrypt(models.CharField(default='000000000')),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
