# Generated by Django 4.2.5 on 2023-11-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0022_user_student_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment_file',
            field=models.FileField(null=True, upload_to='ilmoweb/static/upload/'),
        ),
    ]
