# Generated by Django 4.2.5 on 2023-11-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0023_report_comment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='filename',
            new_name='report_file',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_name',
            new_name='report_file_name',
        ),
        migrations.AddField(
            model_name='report',
            name='comment_file_name',
            field=models.CharField(default=''),
        ),
    ]
