# Generated by Django 4.2.5 on 2023-11-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoweb', '0024_rename_filename_report_report_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
